fix/ notification docker file

diff --git a/notification/Dockerfile b/notification/Dockerfile
--- a/notification/Dockerfile
+++ b/notification/Dockerfile
@@ -2,16 +2,16 @@ FROM golang:1.20.1 as builder
 
 RUN apt-get update &&\
     apt-get -y install sysv-rc-conf
-WORKDIR /go/src
-RUN mkdir notification
+RUN mkdir -p /go/src/notification
 WORKDIR /go/src/notification
 COPY . .
-RUN go build notification.go
+RUN test -f notification.go || echo "notification.go not found"
+RUN go build .
 
-FROM alpine:3.15.0
-RUN apk add --no-cache ca-certificates
-RUN mkdir /lib64 &&\
-    ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2 &&\
+
+FROM alpine:3.18.2
+RUN apk add --no-cache ca-certificates &&\
+    apk add gcompat &&\
     mkdir /var/log/apl
 COPY --from=builder /go/src/notification/notification /notification
 COPY --from=builder /go/src/notification/config.ini  /
@@ -22,4 +22,4 @@ RUN adduser sys-user --disabled-password &&\
 HEALTHCHECK --interval=5m --timeout=30s \
 CMD curl -f http://localhost:9100/metrics || exit 1
 USER sys-user
-ENTRYPOINT ["./notification"]
+ENTRYPOINT ["sh", "-c", "while true; do sleep 1000; done"]
